# Dependencies
markdown:             redcarpet
highlighter:          pygments

# Permalinks
permalink:            pretty
relative_permalinks:  false

# Site settings
title:                rhythm of Rein
tagline:              'Decide to vibe with the process'
email:                reinhardt.cgr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Focus in 5 4 3 2 1 >> Inhale deeply >>
  Exhale slowly to let go >>
  Then decide to vibe with the process
baseurl:              "" # the subpath of your site, e.g. /blog
url:                  "http://reinhardtcgr.github.io/" # the base hostname & protocol for your site

twitter_username:     rhythmofrein
github_username:      reinhardtcgr
linkedin_username:    reinhardtcagara
salutations:          "\"Before you can change the world around you, you must learn to change the worlds within you\""

# Build settings
markdown:             kramdown

author:
  name:               'Mark Otto'
  url:                https://twitter.com/mdo

# paginate:             5

# Custom vars
version:              2.1.0

github:
  repo:               https://github.com/poole/hyde
